# Inspired by https://github.com/annegentle/create-demo
# and https://github.com/zzsza/github-action-with-python

name: push doc to github pages

env:
  GITHUB_ACTOR: JSS95
  GITHUB_REPOSITORY: JSS95/dipcoat-substrate
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

on: [push]  # modify to push on master after all is done.

jobs:

  build-doc:

    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps: 

      - name: install git and clone repository
        run: |
          apt-get update
          apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
