name: dipcoatsubstrate test

on: [pull_request]

jobs:

  flake8:

    runs-on: ubuntu-latest

    steps: 

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - uses: actions/checkout@v2

      - run: flake8

  pytest:

    needs: flake8

    runs-on: ubuntu-latest

    steps: 

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python

      - uses: actions/checkout@v2

      - run: pytest

  doc:

    needs: pytest

    runs-on: ubuntu-latest

    steps: 

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python matplotlib sphinx numpydoc sphinx_rtd_theme
          pip install .

      - name: build document
        run: |
          cd doc
          make html
